name: bioinfo
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - biopython=1.85
  - contourpy=1.3.2
  - cycler=0.12.1
  - fonttools=4.57.0
  - joblib=1.5.0
  - kiwisolver=1.4.8
  - matplotlib=3.10.3
  - numpy=2.2.5
  - packaging=25.0
  - pandas=2.2.3
  - pillow=11.2.1
  - pyparsing=3.2.3
  - python-dateutil=2.9.0.post0
  - pytz=2025.2
  - scikit-learn=1.6.1
  - scipy[version='>=1.11']
  - six=1.17.0
  - threadpoolctl=3.6.0
  - tzdata
  - mafft
  - tqdm
